/**
 * Capital Brix's own WhatsApp sender.
 *
 * Why this exists at all: the attendance reports were leaving through a
 * Baileys worker that also runs Call Pro AI. One WhatsApp login, two
 * companies. That arrangement cost us twice —
 *
 *   - a "Daily Pulse | Fanbe" generated by Call Pro AI left the founder's
 *     WhatsApp to an outside number and read as though Capital Brix had sent
 *     it (22 September 2026);
 *   - the other worker's own toJid() stripped "@g.us" off a group address, so
 *     every group report was acknowledged with a message id and delivered to
 *     nobody, for as long as the group was configured.
 *
 * Neither was a bug in this repo, and neither was ours to fix. A number of our
 * own ends both: one company per session, one codebase that can be read.
 *
 * It speaks exactly the contract `wa-session` already calls, so switching over
 * is two secrets and nothing else:
 *
 *   GET  /health     no bearer. Per-state session counts. The one call that
 *                    separates "the worker is down" from "the worker is up and
 *                    logged out" — two things that look identical from a
 *                    failed send.
 *   GET  /status     bearer. This session's state and the number it is.
 *   GET  /qr         bearer. The pairing square as a data URI, or null.
 *   POST /reconnect  bearer. Start a socket so a QR appears.
 *   POST /send       bearer. { to, text } -> { ok, id }
 *   GET  /groups     bearer. What this number can post to, with JIDs.
 *
 * It only ever sends. It registers no message handler, keeps no chat history
 * and answers nobody — so a number linked here cannot be used to read the
 * founder's conversations, and there is no path by which another product's
 * message could leave through it.
 */

import express from "express";
import { Boom } from "@hapi/boom";
import pino from "pino";
import QRCode from "qrcode";
import baileys, {
  DisconnectReason,
  fetchLatestBaileysVersion,
  useMultiFileAuthState,
} from "@whiskeysockets/baileys";

const makeWASocket = baileys.default ?? baileys.makeWASocket ?? baileys;

const PORT = Number(process.env.PORT || 8099);
const TOKEN = process.env.WA_TOKEN || "";
const AUTH_DIR = process.env.WA_AUTH_DIR || "./auth";

if (!TOKEN) {
  console.error("WA_TOKEN is not set. Refusing to start: an unauthenticated");
  console.error("sender is a WhatsApp account anyone on the internet can post");
  console.error("from. Set WA_TOKEN to a long random string.");
  process.exit(1);
}

const log = pino({ level: process.env.LOG_LEVEL || "warn" });

/* ── the one session ───────────────────────────────────────────────────── */

const session = {
  sock: null,
  status: "disconnected", // disconnected | connecting | qr | connected | logged-out
  qr: null,               // data URI, or null
  user: null,             // { id, name }
  lastError: "",
  startedAt: null,
};

/** A restart must not cost a QR scan, so credentials live on disk. */
async function start() {
  if (session.sock) return;
  session.status = "connecting";
  session.lastError = "";

  const { state, saveCreds } = await useMultiFileAuthState(AUTH_DIR);
  const { version } = await fetchLatestBaileysVersion();

  const sock = makeWASocket({
    version,
    auth: state,
    logger: log,
    printQRInTerminal: false,
    // This worker sends; it does not read. Not syncing history keeps the
    // founder's conversations out of a process that has no business holding
    // them, and keeps the memory footprint small enough for a shared box.
    syncFullHistory: false,
    markOnlineOnConnect: false,
  });
  session.sock = sock;
  session.startedAt = new Date().toISOString();

  sock.ev.on("creds.update", saveCreds);

  sock.ev.on("connection.update", async (u) => {
    const { connection, lastDisconnect, qr } = u;

    if (qr) {
      // The console renders this straight into an <img src>, and a square is
      // only good for seconds — so it is minted fresh on every offer rather
      // than cached.
      session.qr = await QRCode.toDataURL(qr, { margin: 1, width: 320 });
      session.status = "qr";
    }

    if (connection === "open") {
      session.status = "connected";
      session.qr = null;
      session.lastError = "";
      session.user = { id: sock.user?.id ?? null, name: sock.user?.name ?? null };
    }

    if (connection === "close") {
      const code = new Boom(lastDisconnect?.error)?.output?.statusCode;
      session.sock = null;
      session.user = null;

      if (code === DisconnectReason.loggedOut) {
        // Logged out is not a network blip: the phone unlinked this device and
        // the stored credentials are dead. Reconnecting in a loop here would
        // spin forever and hide the one fact that matters, which is that
        // somebody has to scan again. Say so and stop.
        session.status = "logged-out";
        session.lastError = "This WhatsApp is logged out. Scan the QR again.";
        return;
      }

      session.status = "connecting";
      session.lastError = String(lastDisconnect?.error ?? "").slice(0, 300);
      setTimeout(() => start().catch(() => {}), 3000);
    }
  });
}

/* ── addressing ────────────────────────────────────────────────────────── */

/**
 * Turn what a caller wrote into an address WhatsApp will recognise.
 *
 * The rule that matters most is the first one. The worker this replaces did
 * `String(phone).replace(/\D/g, "") + "@s.whatsapp.net"` on everything it was
 * handed — so `120363040760612538@g.us` became a personal JID for an account
 * that does not exist, and Baileys returned a message id for it. Every group
 * report was logged ok and delivered to nobody. An address that already names
 * its own domain is already an address: return it untouched.
 *
 * India is the only country this office dials, so a bare ten digits gets +91
 * rather than being sent to a number nobody holds. A message id is not
 * delivery — the whole point of both rules.
 */
function toJid(raw) {
  const v = String(raw ?? "").trim();
  if (!v) return "";
  if (v.includes("@")) return v;

  let d = v.replace(/\D/g, "");
  if (d.length === 11 && d.startsWith("0")) d = d.slice(1);
  if (d.length === 10) d = `91${d}`;
  return `${d}@s.whatsapp.net`;
}

/* ── http ──────────────────────────────────────────────────────────────── */

const app = express();
app.use(express.json({ limit: "256kb" }));

const bearer = (req, res, next) => {
  const given = (req.headers.authorization ?? "").replace(/^Bearer\s+/i, "");
  if (given !== TOKEN) return res.status(401).json({ error: "not authorised" });
  next();
};

/**
 * /health carries no bearer on purpose.
 *
 * It is the call that says whether anything is listening at all, and it must
 * keep answering when the token is wrong or the session is dead — those are
 * exactly the moments somebody is asking. It reveals a count per state and
 * nothing about the account.
 */
app.get("/health", (_req, res) => {
  res.json({
    ok: true,
    product: "capital-brix",
    states: { [session.status]: 1 },
    last_error: session.lastError || undefined,
    started_at: session.startedAt,
  });
});

app.get("/status", bearer, (_req, res) => {
  res.json({
    status: session.status,
    user: session.user,
    lastError: session.lastError || undefined,
  });
});

app.get("/qr", bearer, async (_req, res) => {
  if (session.status === "connected") return res.json({ status: "connected", qr: null });
  if (!session.sock) start().catch(() => {});
  res.json({ status: session.status, qr: session.qr });
});

app.post("/reconnect", bearer, async (_req, res) => {
  try {
    if (session.sock) {
      try { session.sock.end(undefined); } catch { /* already gone */ }
      session.sock = null;
    }
    session.qr = null;
    await start();
    res.json({ ok: true, status: session.status });
  } catch (e) {
    res.status(500).json({ ok: false, error: String(e).slice(0, 300) });
  }
});

app.get("/groups", bearer, async (_req, res) => {
  if (session.status !== "connected") {
    return res.status(503).json({ error: "not connected", status: session.status });
  }
  try {
    const all = await session.sock.groupFetchAllParticipating();
    const groups = Object.values(all).map((g) => ({
      id: g.id,
      subject: g.subject,
      size: g.participants?.length ?? null,
    }));
    res.json({ groups });
  } catch (e) {
    res.status(500).json({ error: String(e).slice(0, 300) });
  }
});

app.post("/send", bearer, async (req, res) => {
  const { to, text } = req.body ?? {};
  const jid = toJid(to);
  if (!jid) return res.status(400).json({ error: "a number or group id is required" });
  if (!text) return res.status(400).json({ error: "text is required" });

  if (session.status !== "connected") {
    // 503 rather than a cheerful ok: the caller logs this, and the whole
    // reason this module keeps being debugged is messages that reported
    // success and never arrived.
    return res.status(503).json({
      error: session.lastError || "This WhatsApp is not connected.",
      status: session.status,
    });
  }

  try {
    const sent = await session.sock.sendMessage(jid, { text: String(text) });
    res.json({ ok: true, id: sent?.key?.id ?? null, to: jid });
  } catch (e) {
    res.status(502).json({ ok: false, error: String(e).slice(0, 300), to: jid });
  }
});

app.listen(PORT, () => {
  console.log(`Capital Brix WhatsApp worker listening on ${PORT}`);
  start().catch((e) => console.error("start failed:", e));
});
